### ISSUE TITLE
RDFClosure dependency in the code breaks at least pyshacl CLI completely

### ISSUE THREAD

**Issue by rmeissn** [RDFLib/pySHACL#10]
It seems like RDFClosure has been renamed to [OWL-RL](https://github.com/RDFLib/OWL-RL) and that RDFClosure has been removed from the online repositories. Thus it's not installed as a dependency for pyshacl and thus pyshacl throws a lot of ModuleNotFoundErrors. E.g.:

```
### pyshacl --help
Traceback (most recent call last):
  File "/usr/local/bin/pyshacl", line 17, in <module>
    from pyshacl import validate
  File "/usr/local/lib/python3.7/site-packages/pyshacl/__init__.py", line 3, in <module>
    from pyshacl.validate import validate
  File "/usr/local/lib/python3.7/site-packages/pyshacl/validate.py", line 12, in <module>
    from pyshacl.inference import CustomRDFSSemantics, CustomRDFSOWLRLSemantics
  File "/usr/local/lib/python3.7/site-packages/pyshacl/inference/__init__.py", line 2, in <module>
    from .custom_rdfs_closure import CustomRDFSSemantics, CustomRDFSOWLRLSemantics
  File "/usr/local/lib/python3.7/site-packages/pyshacl/inference/custom_rdfs_closure.py", line 2, in <module>
    from RDFClosure.RDFSClosure import RDFS_Semantics as OrigRDFSSemantics
ModuleNotFoundError: No module named 'RDFClosure'
```

I'm using version 0.9.7 of pyshacl from pypi and the issue happens for each command of pyshacl, I have tested so far.

**Comment by ashleysommer** [comment]
Thank you for reporting this.
I thought I changed all usages of RDFSClosure to owlrl for the 0.9.7 release, but evidently I missed the ones in the custom_refs_closure.py file.
I will release a 0.9.8 with this fixed asap.

**Comment by ashleysommer** [comment]
Fixed in https://github.com/RDFLib/pySHACL/commit/d86a00c44cc5f59101c2e1b765dca3846a6f2997
Thanks @rmeissn

**Comment by rmeissn** [comment]
This is not resolved for me with v0.9.8.
```
### sudo pip uninstall pyshacl
### sudo pip install pyshacl
### sudo pip show pyshacl
Name: pyshacl
Version: 0.9.8
Summary: Python SHACL Validator
Home-page: https://github.com/RDFLib/pySHACL/
...
Location: /usr/lib/python2.7/site-packages
Requires: rdflib, rdflib-jsonld, owlrl
...
### pyshacl --help
pyshacl --help
Traceback (most recent call last):
  File "/usr/local/bin/pyshacl", line 17, in <module>
    from pyshacl import validate
  File "/usr/local/lib/python3.7/site-packages/pyshacl/__init__.py", line 3, in <module>
    from pyshacl.validate import validate
  File "/usr/local/lib/python3.7/site-packages/pyshacl/validate.py", line 12, in <module>
    from pyshacl.inference import CustomRDFSSemantics, CustomRDFSOWLRLSemantics
  File "/usr/local/lib/python3.7/site-packages/pyshacl/inference/__init__.py", line 2, in <module>
    from .custom_rdfs_closure import CustomRDFSSemantics, CustomRDFSOWLRLSemantics
  File "/usr/local/lib/python3.7/site-packages/pyshacl/inference/custom_rdfs_closure.py", line 2, in <module>
    from RDFClosure.RDFSClosure import RDFS_Semantics as OrigRDFSSemantics
ModuleNotFoundError: No module named 'RDFClosure'
```

**Comment by ashleysommer** [comment]
@rmeissn
It looks like you've installed pyshcal 0.9.8 using pip for python 2.7, into `/usr/lib/python2.7/site-packages`, but when you run the `pyshacl` script it executes from `/usr/local/lib/python3.7/site-packages/pyshacl/`.

I think that is still an old version.

Try:
```
sudo pip3 uninstall pyshacl
sudo pip3 install pyshacl
```

**Comment by rmeissn** [comment]
You're right. I've accidentally used pip instead of pip3. Thanks for pointing me to this!
v.0.9.8 works as expected.
