### ISSUE TITLE
error using python module

### ISSUE THREAD

**Issue by sanuann** [RDFLib/pySHACL#44]
I am trying to validate a data graph with it corresponding shapes graph. When I use the commandline method it works fine. However I get an erro on using the python module.

I am doing this:
```
r = validate(data_graph, shacl_graph='./validation/ActivityShape.ttl', ont_graph=None, advanced=True, inference='rdfs', abort_on_error=False)
conforms, results_graph, results_text = r
```
I get the following error: 
```
Traceback (most recent call last):
  File "validation/test1.py", line 64, in <module>
    r = validate(data_graph=data_graph, shacl_graph='./validation/ActivityShape.ttl', ont_graph=None, advanced=True, inference='rdfs', abort_on_error=False)
  File "/Users/sanuann/validation-env/lib/python3.6/site-packages/pyshacl/validate.py", line 253, in validate
    do_owl_imports=False)  # no imports on data_graph
  File "/Users/sanuann/validation-env/lib/python3.6/site-packages/pyshacl/rdfutil/load.py", line 110, in load_from_source
    first_char = source[0]
IndexError: string index out of range
```

What am I doing wrong?

**Comment by ashleysommer** [comment]
Hi @sanuann,
Thanks for your interest in pySHACL.

It looks like the rdf loader is crashing while parsing your whatever is in your `data_graph` variable. Seems like it's an empty string?

Can you post more of your example code please?

**Comment by sanuann** [comment]
hi @ashleysommer thanks for looking into this. sorry, i made some mistake in the `data_graph` variable. The above error is resolved but now it shows different error. Here is what I am doing:

```
url = 'https://raw.githubusercontent.com/ReproNim/reproschema/master/activities/PHQ-9/phq9_schema'
data = json.loads(urlopen(url).read().decode("utf-8"))

data_graph = jsonld.normalize(data, {'algorithm': 'URDNA2015', 'format':'application/n-quads'})

r = validate(data_graph, shacl_graph='./validation/ActivityShape.ttl', advanced=True, inference='rdfs', abort_on_error=False, debug=True)
conforms, results_graph, results_text = r
```

The error is as follows:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "validation/test1.py", line 168, in <module>
    r = validate(data_graph, shacl_graph='./validation/ActivityShape.ttl', advanced=True, inference='rdfs', abort_on_error=False, debug=True)
  File "/Users/sanuann/validation-env/lib/python3.6/site-packages/pyshacl/validate.py", line 253, in validate
    do_owl_imports=False)  # no imports on data_graph
  File "/Users/sanuann/validation-env/lib/python3.6/site-packages/pyshacl/rdfutil/load.py", line 238, in load_from_source
    g.parse(source=source, format=rdf_format, publicID=public_id)
  File "/Users/sanuann/validation-env/lib/python3.6/site-packages/rdflib/graph.py", line 1639, in parse
    c = ConjunctiveGraph.parse(self, source, publicID, format, location, file, data, **args)
  File "/Users/sanuann/validation-env/lib/python3.6/site-packages/rdflib/graph.py", line 1496, in parse
    context.parse(source, publicID=publicID, format=format, **args)
  File "/Users/sanuann/validation-env/lib/python3.6/site-packages/rdflib/graph.py", line 1043, in parse
    parser.parse(source, self, **args)
  File "/Users/validation-env/lib/python3.6/site-packages/rdflib/plugins/parsers/rdfxml.py", line 578, in parse
    self._parser.parse(source)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/sax/expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:7: not well-formed (invalid token)
```

Link to the shapes graph used: https://raw.githubusercontent.com/ReproNim/reproschema/master/validation/ActivityShape.ttl

Note: when I use the command line tool to validate i.e.
 `pyshacl -s validation/ActivityShape.ttl -m -i rdfs -a -f human test1.ttl` it results in `Conforms: True`

**Comment by ashleysommer** [comment]
Hi @sanuann 
The problem now is the rdf loader thinks your data file format is rdf/xml. If it's actually turtle, you'll have to specify something like:

`r = validate(data_graph, data_graph_format="ttl", shacl_graph='./validation/ActivityShape.ttl', advanced=True, inference='rdfs', abort_on_error=False, debug=True)
conforms, results_graph, results_text = r`

**Comment by sanuann** [comment]
thanks @ashleysommer !
